// priv/static/admin/src/lib/Login.svelte
<!------------------------------------------------------------------------------------------------------
  A login dialog box
------------------------------------------------------------------------------------------------------->
<script lang="ts">
    // @ts-nocheck

    import { mutation } from 'svelte-apollo';
    import { LOGIN } from './Graphql.svelte';
    import type { Session } from './Graphql.svelte';
    import { convertErrorMessage } from './ErrorMessages.svelte';
	import { createEventDispatcher } from 'svelte';

    import { Card, Text, Divider, Input, Button, Grid, Column, Icon, Header, Content, Image, Description, Actions } from 'svelte-fomantic-ui';

    const dispatch = createEventDispatcher();

    // -------------------------------------------------------------------------------------------------
    // Parameters
    // -------------------------------------------------------------------------------------------------
    // export let successfulLogin : (login_data: Session) => void; // Function to call when login success
    // export let closeLoginDialog : () => void;                   // Function to call to close dialog

    // -------------------------------------------------------------------------------------------------
    // Variables
    // -------------------------------------------------------------------------------------------------
    let upi : string = "";                                      // UPI string being entered
    let password : string = "";                                 // Password string being entered
    let errorMessage : string = "";                             // Error message

    // -------------------------------------------------------------------------------------------------
    // Functions
    // -------------------------------------------------------------------------------------------------
    // Check for enter key and call submit when detected
    const handleKeydown = (event:any) => {
		if (event.key === 'Enter') {
            handleSubmit();
        }
    }

    // The GraphQL mutation structure for login
    const doLogin = mutation(LOGIN);

    // What do do when the enter key or login button is pressed
    const handleSubmit = () => {
        doLogin({ variables: { upi, password } })
        .then((result:any) => {
            console.log(result.data.login);

            dispatch ('login', { message : 'success', data : result.data.login });
        })
        .catch((error : { graphQLErrors : [{ message : string }]}) => {
            errorMessage = convertErrorMessage(error.graphQLErrors[0].message);
        });
    }

    function closeLogin () {
        dispatch ('login', { message : 'close', data : {}})
    }
</script>
<!----------------------------------------------------------------------------------------------------->



<!------------------------------------------------------------------------------------------------------
Styles
------------------------------------------------------------------------------------------------------->
<style>
    
</style>
<!----------------------------------------------------------------------------------------------------->



<!------------------------------------------------------------------------------------------------------
Layout
------------------------------------------------------------------------------------------------------->
<Icon close/>
<Header ui h4 center aligned>
    Log in to the booking system
</Header>
<Content>
    <Description>
        <Input ui fluid>
            <Input placeholder='UPI' bind:value={upi} on:keydown={handleKeydown} />
        </Input>
        <Divider ui small/>
        <Input ui fluid>
            <Input placeholder='Password' bind:value={password} on:keydown={handleKeydown} type='password' />
        </Input>
    </Description>
    {#if errorMessage}
        <Header ui h5 medium red center aligned>{errorMessage}</Header>
    {/if}
</Content>
<Actions>
    <Grid ui two column>
        <Column>
            <Button ui fluid blue on:click={closeLogin}>
                Cancel
            </Button>
        </Column>
        <Column>
            <Button ui fluid green on:click={handleSubmit}>
                Log in
            </Button>
        </Column>
    </Grid>
</Actions>
<!----------------------------------------------------------------------------------------------------->

// priv/static/react/labbookings/src/Login.js
import React, { useState } from 'react';
import 'semantic-ui-css/semantic.min.css';
import { Form, Divider, Grid, Button, Modal, Header } from 'semantic-ui-react';
import GraphQL from './graphql';
import {
    ApolloProvider,
    useMutation,
	gql
  } from "@apollo/client";



// ----------------------------------------------------------------------------------------------------
// Do the login view
// ----------------------------------------------------------------------------------------------------
function View(args)
{
	// Set props and state
	const props = args.props;

	const MUTATION = gql`mutation login($upi: String!, $password: String!) { login (upi: $upi, password: $password) { sessionid upi } }`
	
	const [state, setState] = useState({
		upi: "",
		password: "",
		set: (name, value) => { setState( previousState => { return { ...previousState, [name]: value }} ); }
	});

	// The GraphQL function being used here
	const [login] = useMutation(MUTATION);

	// Do the actual login when the user presses the button
	let DoLogin = () =>
	{		
		login({variables: { upi: state.upi, password: state.password}})
		.then(result => props.loggedin(result.data.login))
		.catch(error => {
			console.debug(error);
			props.error(error)
		})
	};

	// Hand the keypresses and changes in the UI
	let handleKeyPress = (e) => { if (e.charCode === 13) { DoLogin(); } }
	let handleChange = (e, { name, value }) => { state.set([name], value); };

	// The main UI
	return (
		<Modal open={true} size='tiny' >
			<Modal.Content>
			<Header as='h4' textAlign='center'>
				<span>LabBookings WebApp.</span><br/><span>Please log in.</span><br/>
				<span>{props.errorMessage}</span>
			</Header>
			<Divider />
			<Grid columns='one'>
				<Grid.Row>
				<Grid.Column>
					<Form>
					<Form.Field>
						<Form.Input placeholder="UPI" name="upi" type="text" value={state.upi} onKeyPress={handleKeyPress} onChange={handleChange}/>
					</Form.Field>
					<Form.Field>
						<Form.Input placeholder="Password" name="password" type="password" value={state.password} onKeyPress={handleKeyPress} onChange={handleChange}/>
					</Form.Field>
					</Form>
				</Grid.Column>
				</Grid.Row>
			</Grid>
			</Modal.Content>
			<Modal.Actions style={{ paddingLeft: '1.5em', paddingRight: '1.5em' }}>
			<Grid columns='one'>
				<Grid.Row>
				<Grid.Column>
					<Button fluid basic color='green' onClick={DoLogin}>Log in</Button>
				</Grid.Column>
				</Grid.Row>
			</Grid>
			</Modal.Actions>
		</Modal>
	)
}
// ----------------------------------------------------------------------------------------------------



// ----------------------------------------------------------------------------------------------------
// Main Function
// ----------------------------------------------------------------------------------------------------
export default function Login(props) { return (<ApolloProvider client={GraphQL.client}> <View props={props} /> </ApolloProvider>); }
// ----------------------------------------------------------------------------------------------------
