// priv/static/react/labbookings/src/Login.js
import React, { useState } from 'react';
import 'semantic-ui-css/semantic.min.css';
import { Form, Divider, Grid, Button, Modal, Header } from 'semantic-ui-react';
import GraphQL from './graphql';
import {
    ApolloProvider,
    useMutation,
	gql
  } from "@apollo/client";



// ----------------------------------------------------------------------------------------------------
// Do the login view
// ----------------------------------------------------------------------------------------------------
function View(args)
{
	// Set props and state
	const props = args.props;

	const MUTATION = gql`mutation login($upi: String!, $password: String!) { login (upi: $upi, password: $password) { sessionid upi } }`
	
	const [state, setState] = useState({
		upi: "",
		password: "",
		set: (name, value) => { setState( previousState => { return { ...previousState, [name]: value }} ); }
	});

	// The GraphQL function being used here
	const [login] = useMutation(MUTATION);

	// Do the actual login when the user presses the button
	let DoLogin = () =>
	{		
		login({variables: { upi: state.upi, password: state.password}})
		.then(result => props.loggedin(result.data.login))
		.catch(error => {
			console.debug(error);
			props.error(error)
		})
	};

	// Hand the keypresses and changes in the UI
	let handleKeyPress = (e) => { if (e.charCode === 13) { DoLogin(); } }
	let handleChange = (e, { name, value }) => { state.set([name], value); };

	// The main UI
	return (
		<Modal open={true} size='tiny' >
			<Modal.Content>
			<Header as='h4' textAlign='center'>
				<span>LabBookings WebApp.</span><br/><span>Please log in.</span><br/>
				<span>{props.errorMessage}</span>
			</Header>
			<Divider />
			<Grid columns='one'>
				<Grid.Row>
				<Grid.Column>
					<Form>
					<Form.Field>
						<Form.Input placeholder="UPI" name="upi" type="text" value={state.upi} onKeyPress={handleKeyPress} onChange={handleChange}/>
					</Form.Field>
					<Form.Field>
						<Form.Input placeholder="Password" name="password" type="password" value={state.password} onKeyPress={handleKeyPress} onChange={handleChange}/>
					</Form.Field>
					</Form>
				</Grid.Column>
				</Grid.Row>
			</Grid>
			</Modal.Content>
			<Modal.Actions style={{ paddingLeft: '1.5em', paddingRight: '1.5em' }}>
			<Grid columns='one'>
				<Grid.Row>
				<Grid.Column>
					<Button fluid basic color='green' onClick={DoLogin}>Log in</Button>
				</Grid.Column>
				</Grid.Row>
			</Grid>
			</Modal.Actions>
		</Modal>
	)
}
// ----------------------------------------------------------------------------------------------------



// ----------------------------------------------------------------------------------------------------
// Main Function
// ----------------------------------------------------------------------------------------------------
export default function Login(props) { return (<ApolloProvider client={GraphQL.client}> <View props={props} /> </ApolloProvider>); }
// ----------------------------------------------------------------------------------------------------

// priv/static/bookings/src/lib/Login.svelte
<!------------------------------------------------------------------------------------------------------
  Login dialog box

  Author: Dr. Roy C. Davies
  Created: June 2023
  Contact: roy.c.davies@ieee.org
------------------------------------------------------------------------------------------------------->
<script lang="ts">

    import { behavior, Modal, Message, Content, Image, Actions, Button, Form, Field, Label, Input } from "svelte-fomantic-ui";
    import { mutation } from 'svelte-apollo';
    import { LOGIN } from './Graphql.svelte';
    import { convertErrorMessage } from './ErrorMessages.svelte';
	import { createEventDispatcher } from 'svelte';

    // -------------------------------------------------------------------------------------------------
    // Parameters
    // -------------------------------------------------------------------------------------------------
    export let id: string="Login_Dialog";
    // -------------------------------------------------------------------------------------------------



    // -------------------------------------------------------------------------------------------------
    // Variables
    // -------------------------------------------------------------------------------------------------
    let upi : string = "";                                      // UPI string being entered
    let password : string = "";                                 // Password string being entered
    let errorMessage : string = "";                             // Error message
    const dispatch = createEventDispatcher();                   // Event dispatcher

    // -------------------------------------------------------------------------------------------------
    // Functions
    // -------------------------------------------------------------------------------------------------

    // The GraphQL mutation structure for login
    const doLogin = mutation(LOGIN);

    // What do do when the enter key or login button is pressed
    const handleSubmit = () => {
        console.log("LOGGING IN", upi, password);
        doLogin({ variables: { upi, password } })
        .then((result:any) => {
            errorMessage="";
            behavior(id, "hide"); 
            dispatch ('login', { message : 'success', data : result.data.login });
        })
        .catch((error : { graphQLErrors : [{ message : string }]}) => {
            errorMessage = convertErrorMessage(error.graphQLErrors[0].message);
        });
    }

    function closeLogin () {
        errorMessage="";
        behavior(id, "hide"); 
        dispatch ('login', { message : 'close', data : {}})
    }
</script>
<!----------------------------------------------------------------------------------------------------->



<!------------------------------------------------------------------------------------------------------
Styles
------------------------------------------------------------------------------------------------------->
<style>

</style>
<!----------------------------------------------------------------------------------------------------->



<!------------------------------------------------------------------------------------------------------
Layout
------------------------------------------------------------------------------------------------------->
<Modal ui tiny {id}>
    <Content>
        <Form ui>
            <Image ui src="/images/logo.png"/>
            <Field>
                <Label input>User name</Label>
                <Input text placeholder="User name" bind:value={upi}/>
            </Field>
            <Field>
                <Label input>Password</Label>
                <Input password placeholder="Password" bind:value={password}/>
            </Field>
        </Form>
        {#if errorMessage!==""}
            <Message ui error>{errorMessage}</Message>
        {/if}
    </Content>
    <Actions>
        <Button ui red on:click={()=>{closeLogin();}}>Cancel</Button>
        <Button ui green on:click={()=>{handleSubmit();}}>Log in</Button>
    </Actions>
</Modal>
<!----------------------------------------------------------------------------------------------------->
